version: 2

models:
  - name: stg_customers
    config:
      tags: ["staging", "PII"]
    columns:
      - name: customer_id

    tests:
      - elementary.volume_anomalies:
          time_bucket:
            period: day
            count: 1
          sensitivity: 6
          days_back: 14
          backfill_days: 2
          seasonality: day_of_week
          timestamp_column: created_at
          config:
            tags:
              - kl;kl;k
              - kjhljkl
            severity: error
          meta:
            owner:
              - fdg
            description: Checking for anomalies in the size and growth of a table by comparing the row count of each 1 days period to the last 14 days
  - name: stg_orders
    config:
      tags: ["staging", "finance"]
    columns:
      - name: order_id
      - name: status

  - name: stg_payments
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
      - name: payment_method

  - name: stg_signups
    config:
      tags: ["staging", "PII"]
    columns:
      - name: signup_id
      - name: customer_email
