version: 2

models:
  - name: stg_customers
    config:
      tags: ["staging", "PII"]
    columns:
      - name: customer_id

  - name: stg_orders
    config:
      tags: ["staging", "finance"]
    columns:
      - name: order_id
      - name: status

  - name: stg_payments
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
      - name: payment_method

    tests:
      - elementary.dimension_anomalies:
          time_bucket:
            period: day
            count: 1
          sensitivity: 3
          days_back: 14
          backfill_days: 2
          where_expression: event_name = 'pasten'
          seasonality: day_of_week
          timestamp_column: dasdsa
          dimensions:
            - platform
            - country
            - event_name
          anomaly_direction: spike
          config:
            tags:
              - adsad
            severity: warn
          meta:
            description: fjsdlfjsldfklj
  - name: stg_signups
    config:
      tags: ["staging", "PII"]
    columns:
      - name: signup_id
      - name: customer_email
