version: 2

models:
  - name: stg_customers
    config:
      tags: ["staging", "PII"]
    columns:
      - name: customer_id

    tests:
      - elementary.volume_anomalies:
          time_bucket:
            period: hour
            count: 4
          sensitivity: 3
          days_back: 14
          backfill_days: 2
          timestamp_column: updated_at
          config:
            tags:
              - finance
            severity: error
          meta:
            owner:
              - '@idan'
            description: Checking for anomalies in the size and growth of a table by comparing the row count of each 4 hours period to the last 14 days
  - name: stg_orders
    config:
      tags: ["staging", "finance"]
    columns:
      - name: order_id
      - name: status

    tests:
      - elementary.volume_anomalies:
          time_bucket:
            period: hour
            count: 4
          sensitivity: 3
          days_back: 14
          backfill_days: 2
          timestamp_column: updated_at
          config:
            tags:
              - finance
            severity: error
          meta:
            owner:
              - '@idan'
            description: Checking for anomalies in the size and growth of a table by comparing the row count of each 4 hours period to the last 14 days
  - name: stg_payments
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
      - name: payment_method

    tests:
      - elementary.volume_anomalies:
          time_bucket:
            period: hour
            count: 4
          sensitivity: 3
          days_back: 14
          backfill_days: 2
          timestamp_column: updated_at
          config:
            tags:
              - finance
            severity: error
          meta:
            owner:
              - '@idan'
            description: Checking for anomalies in the size and growth of a table by comparing the row count of each 4 hours period to the last 14 days
  - name: stg_signups
    config:
      tags: ["staging", "PII"]
    columns:
      - name: signup_id
      - name: customer_email
    tests:
      - elementary.volume_anomalies:
          time_bucket:
            period: hour
            count: 4
          sensitivity: 3
          days_back: 14
          backfill_days: 2
          timestamp_column: updated_at
          config:
            tags:
              - finance
            severity: error
          meta:
            owner:
              - '@idan'
            description: Checking for anomalies in the size and growth of a table by comparing the row count of each 4 hours period to the last 14 days
