version: 2

models:
  - name: stg_customers
    config:
      tags: ["staging", "PII"]
    columns:
      - name: customer_id

        tests:
          - unique:
              config:
                severity: error
              meta:
                description: The column should contain only unique values
  - name: stg_orders
    config:
      tags: ["staging", "finance"]
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: error
              meta:
                description: The column should contain only unique values
      - name: status

      - name: customer_id
        tests:
          - unique:
              config:
                severity: error
              meta:
                description: The column should contain only unique values
  - name: stg_payments
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                severity: error
              meta:
                description: The column should contain only unique values
      - name: payment_method

      - name: order_id
        tests:
          - unique:
              config:
                severity: error
              meta:
                description: The column should contain only unique values
  - name: stg_signups
    config:
      tags: ["staging", "PII"]
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                severity: error
              meta:
                description: The column should contain only unique values
      - name: customer_email
      - name: customer_id
        tests:
          - unique:
              config:
                severity: error
              meta:
                description: The column should contain only unique values
