version: 2

models:
  - name: stg_customers
    config:
      tags: ["staging", "PII"]
    columns:
      - name: customer_id

  - name: stg_orders
    config:
      tags: ["staging", "finance"]
    columns:
      - name: order_id
      - name: status

  - name: stg_payments
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
      - name: payment_method

    tests:
      - elementary.volume_anomalies:
          time_bucket:
            period: day
            count: 1
          sensitivity: 3
          days_back: 14
          backfill_days: 2
          timestamp_column: col1
          anomaly_direction: spike
          config:
            severity: error
          meta:
            description: Checking for spikes in the size and growth of a table by comparing the row count of each 1 days period to the last 14 days
  - name: stg_signups
    config:
      tags: ["staging", "PII"]
    columns:
      - name: signup_id
      - name: customer_email
