version: 2

models:
  - name: stg_customers
    config:
      tags: ["staging", "PII"]
    columns:
      - name: customer_id

    tests:
      - elementary.freshness_anomalies:
          time_bucket:
            period: hour
            count: 1
          sensitivity: 2
          days_back: 14
          backfill_days: 3
          where_expression: updated_at is not NULL
          seasonality: day_of_week
          timestamp_column: updated_at
          config:
            tags:
              - pasten
            severity: warn
          meta:
            owner:
              - jessica.jones
            description: Checking for freshness anomalies by looking at a 1 hours period and comparing it to last 14 days
  - name: stg_orders
    config:
      tags: ["staging", "finance"]
    columns:
      - name: order_id
      - name: status

    tests:
      - elementary.freshness_anomalies:
          time_bucket:
            period: hour
            count: 1
          sensitivity: 2
          days_back: 14
          backfill_days: 3
          where_expression: updated_at is not NULL
          seasonality: day_of_week
          timestamp_column: updated_at
          config:
            tags:
              - pasten
            severity: warn
          meta:
            owner:
              - jessica.jones
            description: Checking for freshness anomalies by looking at a 1 hours period and comparing it to last 14 days
  - name: stg_payments
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
      - name: payment_method

    tests:
      - elementary.freshness_anomalies:
          time_bucket:
            period: hour
            count: 1
          sensitivity: 2
          days_back: 14
          backfill_days: 3
          where_expression: updated_at is not NULL
          seasonality: day_of_week
          timestamp_column: updated_at
          config:
            tags:
              - pasten
            severity: warn
          meta:
            owner:
              - jessica.jones
            description: Checking for freshness anomalies by looking at a 1 hours period and comparing it to last 14 days
  - name: stg_signups
    config:
      tags: ["staging", "PII"]
    columns:
      - name: signup_id
      - name: customer_email
    tests:
      - elementary.freshness_anomalies:
          time_bucket:
            period: hour
            count: 1
          sensitivity: 2
          days_back: 14
          backfill_days: 3
          where_expression: updated_at is not NULL
          seasonality: day_of_week
          timestamp_column: updated_at
          config:
            tags:
              - pasten
            severity: warn
          meta:
            owner:
              - jessica.jones
            description: Checking for freshness anomalies by looking at a 1 hours period and comparing it to last 14 days
