version: 2

models:
  - name: customers
    meta:
      owner: "@idan"
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
    config:
      tags: "sales"
      elementary:
        timestamp_column: "signup_date"
    tests:
      - elementary.table_anomalies:
          tags: ["error_test", "regular_tests"]
          meta:
            owner: "@oravidov"
            subscribers: ["@idan", "@maayan"]
          table_anomalies:
            - row_count
          time_bucket:
            period: day
            count: 1
      - elementary.all_columns_anomalies:
          column_anomalies: ["null_count"]

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - elementary.column_anomalies:
              column_anomalies: ["null_percent"]
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10
              config:
                severity: warn
          - dbt.unique:
              tags: ["stability"]

      - name: first_name
        description: Customer's first name. PII.
        tests:
          - dbt_expectations.expect_column_to_exist
          - not_null:
              config:
                store_failures: true

      - name: last_name
        description: Customer's last name. PII.
        tests:
          - dbt_expectations.expect_column_to_exist

      - name: first_order
        description: Date (UTC) of a customer's first order

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order

      - name: number_of_orders
        description: Count of the number of orders a customer has placed

      - name: customer_lifetime_value
        description: Total value (AUD) of a customer's orders

      - name: customer_email
        description: Customer's email. PII.

      - name: signup_date
        description: Date (UTC) of a customer's signup to the online shop.
        tests:
          - dbt_utils.accepted_range:
              min_value: "'2023-01-01 00:00:00'"
              max_value: "{{ dbt_date.now() }}"

      - name: CUSTOMER_ID
        tests:
          - unique:
              config:
                severity: error
              meta:
                description: The column should contain only unique values
  - name: orders
    meta:
      owner: "@oravidov"
    description: This table has basic information about orders, as well as some derived facts based on payments
    config:
      tags: ["finance", "sales"]
      elementary:
        timestamp_column: "order_date"

    tests:
      - elementary.dimension_anomalies:
          dimensions:
            - status

    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'

      - name: amount
        description: Total amount (AUD) of the order

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card

  - name: returned_orders
    description: This table contains all of the returned orders
    config:
      tags: ["finance", "sales"]

    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["returned"]

      - name: amount
        description: Total amount (AUD) of the order

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card


      - name: CUSTOMER_ID
        tests:
          - unique:
              config:
                severity: error
              meta:
                description: The column should contain only unique values
      - name: ORDER_ID
        tests:
          - unique:
              config:
                severity: error
              meta:
                description: The column should contain only unique values
exposures:
  - name: orders_dashboard
    type: application
    maturity: medium
    url: https://elementary.demo.orders
    description: >
      All you need to know about Elementary's orders.
    depends_on:
      - ref('returned_orders')
      - ref('orders')
    owner:
      name: Or
      email: or@elementary-data.com
    tags:
      - sales
    meta:
      platform: Tableau
      workbook: By the Week
      path: ByTheWeek/Jaffles

  - name: customers_dashboard
    type: dashboard
    maturity: high
    url: https://elementary.demo.customers
    description: >
      All you need to know about Elementary's customers.
    depends_on:
      - ref('customers')
    owner:
      name: Or
      email: or@elementary-data.com
    tags:
      - sales
      - marketing
